### ISSUE TITLE
Auction should start in the future

### ISSUE THREAD

**Issue by ketony** [joc-rgb/NFT-Marketplace-Auction#1]
https://github.com/joc-rgb/NFT-Marketplace-Auction/blob/7cbba25857bdcf260bc922dbf68fa84bf133d62b/contracts/EnglishAuctions.solpp#L43

Should this comparison be block.timestamp < _startTime ?

**Comment by joc-rgb** [comment]
You're right. I just fixed it. Thank you so much!
